[features.platforms]
linux = ["linux", "posix"]
darwin = ["darwin", "posix"]
windows = ["windows"]

[features.architectures]
x86_64 = ["amd64"]
arm64 = ["arm64"]

[module.io.file]
base = []
darwin = ["darwin"]
linux = ["linux"]
windows = ["windows"]
amd64 = ["amd64"]
arm64 = ["arm64"]
