pub const VulkanError = error{
    VulkanLibraryNotFound,
    GetInstanceProcAddrNotFound,
    GetDeviceProcAddrNotLoaded,
    FunctionNotFound,
    InvalidParameter,
    OutOfMemory,
    DeviceLost,
    InitializationFailed,
    LayerNotPresent,
    ExtensionNotPresent,
    FeatureNotPresent,
    IncompatibleDriver,
    TooManyObjects,
    FormatNotSupported,
    FragmentedPool,
    Unknown,
    OutOfPoolMemory,
    InvalidExternalHandle,
    Fragmentation,
    InvalidOpaqueCaptureAddress,
    PipelineCompileRequired,
    SurfaceLost,
    NativeWindowInUse,
    OutOfDate,
    ValidationFailed,
    FullScreenExclusiveModeLost,
    ThreadIdle,
    ThreadDone,
    OperationDeferred,
    OperationNotDeferred,
    CompressionExhausted,
};

// Convert VkResult to Zig error
fn resultToError(result: vk.VkResult) VulkanError!void {
    return switch (result) {
        vk.VK_SUCCESS => {},
        vk.VK_NOT_READY => {},
        vk.VK_TIMEOUT => {},
        vk.VK_EVENT_SET => {},
        vk.VK_EVENT_RESET => {},
        vk.VK_INCOMPLETE => {},
        vk.VK_ERROR_OUT_OF_HOST_MEMORY => VulkanError.OutOfMemory,
        vk.VK_ERROR_OUT_OF_DEVICE_MEMORY => VulkanError.OutOfMemory,
        vk.VK_ERROR_INITIALIZATION_FAILED => VulkanError.InitializationFailed,
        vk.VK_ERROR_DEVICE_LOST => VulkanError.DeviceLost,
        vk.VK_ERROR_MEMORY_MAP_FAILED => VulkanError.OutOfMemory,
        vk.VK_ERROR_LAYER_NOT_PRESENT => VulkanError.LayerNotPresent,
        vk.VK_ERROR_EXTENSION_NOT_PRESENT => VulkanError.ExtensionNotPresent,
        vk.VK_ERROR_FEATURE_NOT_PRESENT => VulkanError.FeatureNotPresent,
        vk.VK_ERROR_INCOMPATIBLE_DRIVER => VulkanError.IncompatibleDriver,
        vk.VK_ERROR_TOO_MANY_OBJECTS => VulkanError.TooManyObjects,
        vk.VK_ERROR_FORMAT_NOT_SUPPORTED => VulkanError.FormatNotSupported,
        vk.VK_ERROR_FRAGMENTED_POOL => VulkanError.FragmentedPool,
        vk.VK_ERROR_UNKNOWN => VulkanError.Unknown,
        vk.VK_ERROR_OUT_OF_POOL_MEMORY => VulkanError.OutOfPoolMemory,
        vk.VK_ERROR_INVALID_EXTERNAL_HANDLE => VulkanError.InvalidExternalHandle,
        vk.VK_ERROR_FRAGMENTATION => VulkanError.Fragmentation,
        vk.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS => VulkanError.InvalidOpaqueCaptureAddress,
        vk.VK_PIPELINE_COMPILE_REQUIRED => VulkanError.PipelineCompileRequired,
        vk.VK_ERROR_SURFACE_LOST_KHR => VulkanError.SurfaceLost,
        vk.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR => VulkanError.NativeWindowInUse,
        vk.VK_SUBOPTIMAL_KHR => {},
        vk.VK_ERROR_OUT_OF_DATE_KHR => VulkanError.OutOfDate,
        vk.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR => VulkanError.IncompatibleDriver,
        vk.VK_ERROR_VALIDATION_FAILED_EXT => VulkanError.ValidationFailed,
        vk.VK_ERROR_INVALID_SHADER_NV => VulkanError.ValidationFailed,
        vk.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT => VulkanError.FullScreenExclusiveModeLost,
        vk.VK_THREAD_IDLE_KHR => VulkanError.ThreadIdle,
        vk.VK_THREAD_DONE_KHR => VulkanError.ThreadDone,
        vk.VK_OPERATION_DEFERRED_KHR => VulkanError.OperationDeferred,
        vk.VK_OPERATION_NOT_DEFERRED_KHR => VulkanError.OperationNotDeferred,
        else => VulkanError.Unknown,
    };
}
